//! Generates Rust and TypeScript constants from `constants/*.toml`.
//!
//! Nothing is hand-duplicated between the two codebases. Ever.
//!
//!   cargo run -p codegen           # write the generated files
//!   cargo run -p codegen -- --check  # fail if they are stale (CI)

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::{fs, path::PathBuf};

#[derive(Deserialize)]
struct Platforms {
    platform: Vec<Platform>,
}

#[derive(Deserialize)]
struct Platform {
    id: String,
    display_name: String,
    order_enabled: bool,
    read_host: String,
    impersonate: String,
    app_version: String,
    app_client: String,
}

#[derive(Deserialize)]
struct Statuses {
    state: Vec<State>,
    terminal: Terminal,
}

#[derive(Deserialize)]
struct State {
    id: String,
    to: Vec<String>,
}

#[derive(Deserialize)]
struct Terminal {
    for_address_gc: Vec<String>,
}

/// `blinkit` -> `Blinkit`, `out_for_delivery` -> `OutForDelivery`
fn pascal(s: &str) -> String {
    s.split(['_', '-'])
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + &c.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn root() -> PathBuf {
    // tools/codegen/ -> monorepo/
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("codegen must live at <root>/tools/codegen")
        .to_path_buf()
}

fn main() -> Result<()> {
    let check = std::env::args().any(|a| a == "--check");
    let root = root();

    let platforms: Platforms = toml::from_str(&read(&root, "constants/platforms.toml")?)?;
    let statuses: Statuses = toml::from_str(&read(&root, "constants/status.toml")?)?;
    // Parsed as a generic value: limits are plain scalars that both languages
    // emit verbatim, so a typed struct here would be pure duplication.
    let limits: toml::Value = toml::from_str(&read(&root, "constants/limits.toml")?)?;

    let outputs = [
        (
            "crates/constants/src/generated.rs",
            render_rust(&platforms, &statuses, &limits)?,
        ),
        (
            "packages/constants/src/generated.ts",
            render_ts(&platforms, &statuses, &limits)?,
        ),
    ];

    let mut stale = Vec::new();
    for (rel, content) in &outputs {
        let path = root.join(rel);
        let current = fs::read_to_string(&path).unwrap_or_default();
        if current == *content {
            continue;
        }
        if check {
            stale.push(*rel);
        } else {
            if let Some(dir) = path.parent() {
                fs::create_dir_all(dir)?;
            }
            fs::write(&path, content).with_context(|| format!("writing {rel}"))?;
            println!("wrote {rel}");
        }
    }

    if !stale.is_empty() {
        bail!(
            "generated files are stale relative to constants/*.toml:\n  {}\n\
             run `cargo run -p codegen` and commit the result",
            stale.join("\n  ")
        );
    }
    if check {
        println!("generated files are up to date");
    }
    Ok(())
}

fn read(root: &PathBuf, rel: &str) -> Result<String> {
    fs::read_to_string(root.join(rel)).with_context(|| format!("reading {rel}"))
}

const BANNER: &str = "// @generated by tools/codegen from constants/*.toml — DO NOT EDIT.\n\
                      // Run `cargo run -p codegen` after changing a .toml.\n";

fn render_rust(p: &Platforms, s: &Statuses, limits: &toml::Value) -> Result<String> {
    let mut o = String::from(BANNER);
    o.push_str("#![allow(dead_code)]\n\n");

    // ---- Platform -----------------------------------------------------------
    o.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum Platform {\n");
    for pl in &p.platform {
        o.push_str(&format!("    {},\n", pascal(&pl.id)));
    }
    o.push_str("}\n\npub struct PlatformSpec {\n    pub id: &'static str,\n    pub display_name: &'static str,\n    pub order_enabled: bool,\n    pub read_host: &'static str,\n    pub impersonate: &'static str,\n    pub app_version: &'static str,\n    pub app_client: &'static str,\n}\n\n");
    o.push_str("impl Platform {\n    pub const ALL: &'static [Platform] = &[");
    for pl in &p.platform {
        o.push_str(&format!("Platform::{}, ", pascal(&pl.id)));
    }
    o.push_str("];\n\n    pub const fn spec(self) -> &'static PlatformSpec {\n        match self {\n");
    for pl in &p.platform {
        o.push_str(&format!(
            "            Platform::{} => &PlatformSpec {{ id: {:?}, display_name: {:?}, order_enabled: {}, read_host: {:?}, impersonate: {:?}, app_version: {:?}, app_client: {:?} }},\n",
            pascal(&pl.id), pl.id, pl.display_name, pl.order_enabled,
            pl.read_host, pl.impersonate, pl.app_version, pl.app_client
        ));
    }
    o.push_str("        }\n    }\n}\n\n");

    // ---- OrderState ---------------------------------------------------------
    o.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum OrderState {\n");
    for st in &s.state {
        o.push_str(&format!("    {},\n", pascal(&st.id)));
    }
    o.push_str("}\n\nimpl OrderState {\n    pub const fn as_str(self) -> &'static str {\n        match self {\n");
    for st in &s.state {
        o.push_str(&format!(
            "            OrderState::{} => {:?},\n",
            pascal(&st.id),
            st.id
        ));
    }
    o.push_str("        }\n    }\n\n    /// Exhaustive: adding a state to status.toml forces this to be handled.\n    pub fn can_transition_to(self, next: OrderState) -> bool {\n        matches!((self, next),\n");
    let mut arms = Vec::new();
    for st in &s.state {
        for t in &st.to {
            arms.push(format!(
                "            (OrderState::{}, OrderState::{})",
                pascal(&st.id),
                pascal(t)
            ));
        }
    }
    o.push_str(&arms.join(" |\n"));
    o.push_str("\n        )\n    }\n\n    /// After these, a recipient's supplier-side address may be GC'd.\n    pub const TERMINAL_FOR_ADDRESS_GC: &'static [OrderState] = &[");
    for t in &s.terminal.for_address_gc {
        o.push_str(&format!("OrderState::{}, ", pascal(t)));
    }
    o.push_str("];\n}\n\n");

    // ---- limits -------------------------------------------------------------
    o.push_str("pub mod limits {\n");
    for (section, body) in limits.as_table().context("limits.toml root")? {
        o.push_str(&format!("    pub mod {section} {{\n"));
        for (k, v) in body.as_table().context("limits section")? {
            let (ty, val) = scalar(v)?;
            o.push_str(&format!(
                "        pub const {}: {ty} = {val};\n",
                k.to_uppercase()
            ));
        }
        o.push_str("    }\n");
    }
    o.push_str("}\n");
    Ok(o)
}

fn scalar(v: &toml::Value) -> Result<(&'static str, String)> {
    Ok(match v {
        toml::Value::Integer(i) => ("u64", i.to_string()),
        toml::Value::Boolean(b) => ("bool", b.to_string()),
        toml::Value::String(s) => ("&'static str", format!("{s:?}")),
        other => bail!("limits.toml values must be scalar, got {other:?}"),
    })
}

fn render_ts(p: &Platforms, s: &Statuses, limits: &toml::Value) -> Result<String> {
    let mut o = String::from(BANNER);

    o.push_str("export const PLATFORMS = {\n");
    for pl in &p.platform {
        o.push_str(&format!(
            "  {}: {{ id: {:?}, displayName: {:?}, orderEnabled: {}, readHost: {:?}, impersonate: {:?}, appVersion: {:?}, appClient: {:?} }},\n",
            pl.id, pl.id, pl.display_name, pl.order_enabled,
            pl.read_host, pl.impersonate, pl.app_version, pl.app_client
        ));
    }
    o.push_str("} as const;\n\nexport type Platform = keyof typeof PLATFORMS;\n\n");

    o.push_str("export const ORDER_STATES = [\n");
    for st in &s.state {
        o.push_str(&format!("  {:?},\n", st.id));
    }
    o.push_str("] as const;\n\nexport type OrderState = (typeof ORDER_STATES)[number];\n\n");

    o.push_str("export const ORDER_TRANSITIONS: Record<OrderState, readonly OrderState[]> = {\n");
    for st in &s.state {
        let tos: Vec<String> = st.to.iter().map(|t| format!("{t:?}")).collect();
        o.push_str(&format!("  {:?}: [{}],\n", st.id, tos.join(", ")));
    }
    o.push_str("};\n\n");

    let gc: Vec<String> = s
        .terminal
        .for_address_gc
        .iter()
        .map(|t| format!("{t:?}"))
        .collect();
    o.push_str(&format!(
        "/** After these, a recipient's supplier-side address may be GC'd. */\nexport const TERMINAL_FOR_ADDRESS_GC: readonly OrderState[] = [{}];\n\n",
        gc.join(", ")
    ));

    o.push_str("export const LIMITS = {\n");
    for (section, body) in limits.as_table().context("limits.toml root")? {
        o.push_str(&format!("  {section}: {{\n"));
        for (k, v) in body.as_table().context("limits section")? {
            let (_, val) = scalar(v)?;
            o.push_str(&format!("    {}: {val},\n", camel(k)));
        }
        o.push_str("  },\n");
    }
    o.push_str("} as const;\n");
    Ok(o)
}

fn camel(s: &str) -> String {
    let mut parts = s.split('_');
    let first = parts.next().unwrap_or_default().to_string();
    first + &parts.map(pascal).collect::<String>()
}
