// @generated by tools/codegen from constants/*.toml — DO NOT EDIT.
// Run `cargo run -p codegen` after changing a .toml.
#![allow(dead_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Platform {
    Blinkit,
    Zepto,
    Instamart,
}

pub struct PlatformSpec {
    pub id: &'static str,
    pub display_name: &'static str,
    pub order_enabled: bool,
    pub read_host: &'static str,
    pub impersonate: &'static str,
    pub app_version: &'static str,
    pub app_client: &'static str,
}

impl Platform {
    pub const ALL: &'static [Platform] = &[Platform::Blinkit, Platform::Zepto, Platform::Instamart, ];

    pub const fn spec(self) -> &'static PlatformSpec {
        match self {
            Platform::Blinkit => &PlatformSpec { id: "blinkit", display_name: "Blinkit", order_enabled: true, read_host: "blinkit.com", impersonate: "chrome137", app_version: "18.9.3", app_client: "consumer_web" },
            Platform::Zepto => &PlatformSpec { id: "zepto", display_name: "Zepto", order_enabled: false, read_host: "www.zeptonow.com", impersonate: "chrome137", app_version: "26.3.1", app_client: "android" },
            Platform::Instamart => &PlatformSpec { id: "instamart", display_name: "Swiggy Instamart", order_enabled: false, read_host: "www.swiggy.com", impersonate: "chrome137", app_version: "", app_client: "web" },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OrderState {
    Draft,
    Quoted,
    QuoteStale,
    Authorized,
    Procuring,
    Placed,
    Confirmed,
    OutForDelivery,
    PartialFulfill,
    Delivered,
    Captured,
    Settled,
    ProcurementFailed,
    Abandoned,
    CancelledByPlatform,
    RefundPending,
    RefundIssued,
}

impl OrderState {
    pub const fn as_str(self) -> &'static str {
        match self {
            OrderState::Draft => "DRAFT",
            OrderState::Quoted => "QUOTED",
            OrderState::QuoteStale => "QUOTE_STALE",
            OrderState::Authorized => "AUTHORIZED",
            OrderState::Procuring => "PROCURING",
            OrderState::Placed => "PLACED",
            OrderState::Confirmed => "CONFIRMED",
            OrderState::OutForDelivery => "OUT_FOR_DELIVERY",
            OrderState::PartialFulfill => "PARTIAL_FULFILL",
            OrderState::Delivered => "DELIVERED",
            OrderState::Captured => "CAPTURED",
            OrderState::Settled => "SETTLED",
            OrderState::ProcurementFailed => "PROCUREMENT_FAILED",
            OrderState::Abandoned => "ABANDONED",
            OrderState::CancelledByPlatform => "CANCELLED_BY_PLATFORM",
            OrderState::RefundPending => "REFUND_PENDING",
            OrderState::RefundIssued => "REFUND_ISSUED",
        }
    }

    /// Exhaustive: adding a state to status.toml forces this to be handled.
    pub fn can_transition_to(self, next: OrderState) -> bool {
        matches!((self, next),
            (OrderState::Draft, OrderState::Quoted) |
            (OrderState::Draft, OrderState::Abandoned) |
            (OrderState::Quoted, OrderState::Authorized) |
            (OrderState::Quoted, OrderState::QuoteStale) |
            (OrderState::Quoted, OrderState::Abandoned) |
            (OrderState::QuoteStale, OrderState::Quoted) |
            (OrderState::QuoteStale, OrderState::Abandoned) |
            (OrderState::Authorized, OrderState::Procuring) |
            (OrderState::Authorized, OrderState::ProcurementFailed) |
            (OrderState::Procuring, OrderState::Placed) |
            (OrderState::Procuring, OrderState::ProcurementFailed) |
            (OrderState::Placed, OrderState::Confirmed) |
            (OrderState::Placed, OrderState::CancelledByPlatform) |
            (OrderState::Confirmed, OrderState::OutForDelivery) |
            (OrderState::Confirmed, OrderState::CancelledByPlatform) |
            (OrderState::OutForDelivery, OrderState::Delivered) |
            (OrderState::OutForDelivery, OrderState::PartialFulfill) |
            (OrderState::OutForDelivery, OrderState::CancelledByPlatform) |
            (OrderState::PartialFulfill, OrderState::Delivered) |
            (OrderState::Delivered, OrderState::Captured) |
            (OrderState::Captured, OrderState::Settled) |
            (OrderState::CancelledByPlatform, OrderState::RefundPending) |
            (OrderState::RefundPending, OrderState::RefundIssued)
        )
    }

    /// After these, a recipient's supplier-side address may be GC'd.
    pub const TERMINAL_FOR_ADDRESS_GC: &'static [OrderState] = &[OrderState::Delivered, OrderState::Settled, OrderState::CancelledByPlatform, OrderState::RefundIssued, OrderState::ProcurementFailed, OrderState::Abandoned, ];
}

pub mod limits {
    pub mod address_book {
        pub const GC_BATCH_SIZE: u64 = 5;
        pub const GC_GRACE_HOURS: u64 = 24;
        pub const GC_MAX_DELETE_FAILURES: u64 = 3;
    }
    pub mod coverage {
        pub const PROBE_FAILURES_BEFORE_NEGATIVE: u64 = 3;
    }
    pub mod harness {
        pub const APP_VERSION_POLL_SECONDS: u64 = 900;
        pub const CANARY_INTERVAL_SECONDS: u64 = 600;
    }
    pub mod order_pool {
        pub const AUTH_FRESHNESS_SECONDS: u64 = 600;
        pub const HEALTH_CHECK_SECONDS: u64 = 180;
        pub const LEASE_HEARTBEAT_SECONDS: u64 = 30;
        pub const LEASE_TTL_SECONDS: u64 = 600;
        pub const MAX_LIVE_ORDERS_PER_ACCOUNT: u64 = 1;
    }
    pub mod read_pool {
        pub const BACKOFF_INITIAL_MS: u64 = 1000;
        pub const BACKOFF_MAX_MS: u64 = 60000;
        pub const CIRCUIT_BREAK_FAILURES: u64 = 5;
        pub const HEALTH_CHECK_SECONDS: u64 = 180;
        pub const MAX_CONCURRENT_PER_IDENTITY: u64 = 2;
        pub const REQUESTS_PER_MINUTE: u64 = 30;
    }
}
