// @generated by tools/codegen from constants/*.toml — DO NOT EDIT.
// Run `cargo run -p codegen` after changing a .toml.
export const PLATFORMS = {
  blinkit: { id: "blinkit", displayName: "Blinkit", orderEnabled: true, readHost: "blinkit.com", impersonate: "chrome137", appVersion: "18.9.3", appClient: "consumer_web" },
  zepto: { id: "zepto", displayName: "Zepto", orderEnabled: false, readHost: "www.zeptonow.com", impersonate: "chrome137", appVersion: "26.3.1", appClient: "android" },
  instamart: { id: "instamart", displayName: "Swiggy Instamart", orderEnabled: false, readHost: "www.swiggy.com", impersonate: "chrome137", appVersion: "", appClient: "web" },
} as const;

export type Platform = keyof typeof PLATFORMS;

export const ORDER_STATES = [
  "DRAFT",
  "QUOTED",
  "QUOTE_STALE",
  "AUTHORIZED",
  "PROCURING",
  "PLACED",
  "CONFIRMED",
  "OUT_FOR_DELIVERY",
  "PARTIAL_FULFILL",
  "DELIVERED",
  "CAPTURED",
  "SETTLED",
  "PROCUREMENT_FAILED",
  "ABANDONED",
  "CANCELLED_BY_PLATFORM",
  "REFUND_PENDING",
  "REFUND_ISSUED",
] as const;

export type OrderState = (typeof ORDER_STATES)[number];

export const ORDER_TRANSITIONS: Record<OrderState, readonly OrderState[]> = {
  "DRAFT": ["QUOTED", "ABANDONED"],
  "QUOTED": ["AUTHORIZED", "QUOTE_STALE", "ABANDONED"],
  "QUOTE_STALE": ["QUOTED", "ABANDONED"],
  "AUTHORIZED": ["PROCURING", "PROCUREMENT_FAILED"],
  "PROCURING": ["PLACED", "PROCUREMENT_FAILED"],
  "PLACED": ["CONFIRMED", "CANCELLED_BY_PLATFORM"],
  "CONFIRMED": ["OUT_FOR_DELIVERY", "CANCELLED_BY_PLATFORM"],
  "OUT_FOR_DELIVERY": ["DELIVERED", "PARTIAL_FULFILL", "CANCELLED_BY_PLATFORM"],
  "PARTIAL_FULFILL": ["DELIVERED"],
  "DELIVERED": ["CAPTURED"],
  "CAPTURED": ["SETTLED"],
  "SETTLED": [],
  "PROCUREMENT_FAILED": [],
  "ABANDONED": [],
  "CANCELLED_BY_PLATFORM": ["REFUND_PENDING"],
  "REFUND_PENDING": ["REFUND_ISSUED"],
  "REFUND_ISSUED": [],
};

/** After these, a recipient's supplier-side address may be GC'd. */
export const TERMINAL_FOR_ADDRESS_GC: readonly OrderState[] = ["DELIVERED", "SETTLED", "CANCELLED_BY_PLATFORM", "REFUND_ISSUED", "PROCUREMENT_FAILED", "ABANDONED"];

export const LIMITS = {
  address_book: {
    gcBatchSize: 5,
    gcGraceHours: 24,
    gcMaxDeleteFailures: 3,
  },
  coverage: {
    probeFailuresBeforeNegative: 3,
  },
  harness: {
    appVersionPollSeconds: 900,
    canaryIntervalSeconds: 600,
  },
  order_pool: {
    authFreshnessSeconds: 600,
    healthCheckSeconds: 180,
    leaseHeartbeatSeconds: 30,
    leaseTtlSeconds: 600,
    maxLiveOrdersPerAccount: 1,
  },
  read_pool: {
    backoffInitialMs: 1000,
    backoffMaxMs: 60000,
    circuitBreakFailures: 5,
    healthCheckSeconds: 180,
    maxConcurrentPerIdentity: 2,
    requestsPerMinute: 30,
  },
} as const;
